<!DOCTYPE html>
<html>
<head>
        <?php include_once('css_file.php');?>
	
</head>
<body>

    <?php include_once('Header.php');?>

	<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url(images/resource/tata-bg.jpg) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div><!-- PARALLAX BACKGROUND IMAGE -->
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>Tata Consultancy Services</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="block">
			<div class="container">
				<div class="row">
				 	<div class="col-lg-8 column">
				 		<div class="job-single-sec style3">
				 			<div class="job-wide-devider">
				 				<div class="job-overview divide">
						 			<h3>Company Information</h3>
						 			<ul>
						 				<li><i class="la la-eye"></i><h3>Viewed </h3><span>164</span></li>
						 				<li><i class="la la-file-text"></i><h3>Posted Jobs</h3><span>4</span></li>
						 				<li><i class="la la-map"></i><h3>Locations</h3><span>Mumbai, Maharashtra, India</span></li>
						 			</ul>
						 			<ul>
						 				<li><i class="la la-bars"></i><h3>Categories</h3><span>IT services, It consultancy</span></li>
						 				<li><i class="la la-clock-o"></i><h3>Since</h3><span>1968</span></li>
						 				<li><i class="la la-users"></i><h3>Team Size</h3><span>15</span></li>
						 			</ul>
						 			<ul>
						 				<li><i class="la la-user"></i><h3>Followers</h3><span>15</span></li>
						 			</ul>
						 		</div><!-- Job Overview -->
					 			<div class="job-details">
					 				<h3>Company Information</h3>
					 				<p>Tata Consultancy Services Limited (TCS) is an Indian multinational information technology (IT) service and consulting company headquartered in Mumbai, Maharashtra, India. It is a subsidiary of Tata Group and operates in 149 locations across 45 countries.

									TCS is the largest Indian company by market capitalization.TCS is now placed among the most valuable IT services brands worldwide. In 2015 TCS was ranked 64th overall in the Forbes World's Most Innovative Companies ranking, making it both the highest-ranked IT services company and the top Indian company. It is the world's largest IT services provider. As of 2017, it is ranked tenth on the Fortune India 500 list. In April 2018, TCS became the first Indian IT company to breach $100 billion market capitalization, and second Indian company ever (after Reliance Industries achieved it in 2007) after its market capitalization stood at ₹6,79,332.81 crore ($102.6 billion) on the Bombay Stock Exchange.

									In 2016-2017, Parent company Tata Sons owned 70% of TCS; and more than 70% of Tata Sons' dividends were generated by TCS.In March 2018, Tata Sons decided to sell stocks of TCS worth $1.25 billion in a bulk deal.
									 </p><p><b>History</b></p>
					 				<p><b>1968-2005</b></p><p>
									TCS Limited, initially started as "Tata COMPUTER SYSTEMS" was founded 1968 by division of Tata Sons Limited.Its early contracts included punched card services to sister company TISCO (now Tata Steel), working on an Inter-Branch Reconciliation System for the Central Bank of India, and providing bureau services to Unit Trust of India.

									In 1975, TCS delivered an electronic depository and trading system called SECOM for the Swiss company SIS SegaInterSettle (deutsch); it also developed System X for the Canadian Depository System and automated the Johannesburg Stock Exchange. It associated with a Swiss partner, TKS Teknosoft, which it later acquired.

									In 1980, TCS established India's first dedicated software research and development centre, the Tata Research Development and Design Centre (TRDDC) in Pune.In 1981, it established India's first client-dedicated offshore development centre, set up for clients Tandem. TCS later (1993) partnered with Canada-based software factory Integrity Software Corp, which TCS later acquired.

In anticipation of the Y2K bug and the launch of a unified European currency (Euro), Tata Consultancy Services created the factory model for Y2K conversion and developed software tools which automated the conversion process and enabled third-party developer and client implementation. Towards the end of 1999, TCS decided to offer Decision Support System (DSS) in the domestic market under its Corporate Vice President and Transformation Head Subbu Iyer.
</p>
<p>
<b>2004 to present</b></p><p>
On 25 August 2004, TCS became a Publicly Listed Company.

In 2005, TCS became the first India-based IT services company to enter the bioinformatics market. In 2006, it designed an ERP system for the Indian Railway Catering and Tourism Corporation. By 2008, its e-business activities were generating over US$500 million in annual revenues.

TCS entered the small and medium enterprises market for the first time in 2011, with cloud-based offerings. On the last trading day of 2011, it overtook RIL to achieve the highest market capitalisation of any India-based company. In the 2011/12 fiscal year, TCS achieved annual revenues of over US$10 billion for the first time.

In May 2013, TCS was awarded a six-year contract worth over ₹ 1100 crores to provide services to the Indian Department of Posts. In 2013, the firm moved from the 13th position to 10th position in the League of top 10 global IT services companies and in July 2014, it became the first Indian company with over Rs 5 lakh crore market capitalization.

In Jan 2015, TCS ends RIL's 23-year run as most profitable firm

In Jan 2017, the company announced a partnership with Aurus, Inc., a payments technology company, to deliver payment solutions for retailers using TCS OmniStore, a first of its kind unified store commerce platform. In the same year, TCS China was associated as a joint venture with the Chinese government.

TCS announced its FY19 Q3 results posting 24 percent year-on-year (YoY) rise in profit at Rs 8,105 crore. The stock plunged 2.5 percent intra-day as brokerages cut price target.</p>
					 				<p><b>Poduct and Services</b></p>
					 				<p>TCS and its 67 subsidiaries provide a wide range of information technology-related products and services including application development, business process outsourcing, capacity planning, consulting, enterprise software, hardware sizing, payment processing, software management and technology education services.The firm's established software products are TCS BaNCS and TCS MasterCraft.</p>

<p><b>Service lines</b></p><p>
TCS' services are currently organised into the following service lines (percentage of total TCS revenues in the 2012-13 financial year generated by each respective service line is shown in parentheses):
<ul><li>
Application development and maintenance (43.80%) value;</li>
<li>Asset leverage solutions[clarification needed] (2.70%);</li>
<li>Assurance services (7.70%);</li>
<li>Business process outsourcing (12.50%);</li>
<li>Consulting (2.00%);</li>
<li>Engineering and Industrial services (4.60%);</li>
<li>Enterprise solution (15.21%); and</li>
<li>IT infrastructure services (11.50%).</li></ul> </p>
					 				<p><b>Operations</b></p><p>
TCS has 285 offices across 46 countries and 147 delivery centers in 21 countries. At the same date TCS had a total of 58 subsidiary companies.
</p>
<p><b>Locations</b></p><p>
TCS has operations in the following locations:

<li><b>India:</b> Ahmedabad, Bangalore, Baroda, Bhubaneswar, Chennai, Coimbatore, Delhi, Gandhinagar, Goa, Gurgaon, Guwahati, Hyderabad, Bhopal, Indore, Jamshedpur, Kochi, Kolkata, Lucknow, Mumbai, Nagpur, Noida, Nashik, Patna, Pune, Trivandrum, Varanasi, and Visakhapatnam</li>

<li><b>Asia (excluding India):</b> Bahrain, China, Israel, UAE, Hong Kong, Indonesia, Japan, Malaysia, Philippines, Saudi Arabia, Singapore, South Korea, Taiwan, Thailand, and Qatar</li>

<li><b>Oceania:</b> Australia</li>

<li><b>Africa:</b> South Africa, Morocco (closed)</li>

<li><b>Europe:</b> Belgium, Denmark, Finland, France, Germany, Hungary, Iceland, Republic of Ireland, Italy, Luxembourg, Netherlands, Norway, Portugal, Spain, Sweden, Switzerland, and United Kingdom.</li>

<li><b>North America:</b> Canada, Mexico, and United States.</li>

<li><b>South America:</b> Argentina, Brazil, Chile, Colombia, Ecuador, Peru, and Uruguay.</p></li></ul>
					 			</div>
						 		<div class="recent-jobs">
					 				<h3>Jobs from Business Network</h3>
					 				<div class="job-list-modern">
									 	<div class="job-listings-sec no-border">
											<div class="job-listing wtabs noimg">
												<div class="job-title-sec">
													<h3><a href="#" title="">Web Designer / Developer</a></h3>
													<span>Massimo Artemisis</span>
													<div class="job-lctn"><i class="la la-map-marker"></i>Sacramento, California</div>
												</div>
												<div class="job-style-bx">
													<span class="job-is ft">Full time</span>
													<span class="fav-job"><i class="la la-heart-o"></i></span>
													<i>5 months ago</i>
												</div>
											</div>
											<div class="job-listing wtabs noimg">
												<div class="job-title-sec">
													<h3><a href="#" title="">C Developer (Senior) C .Net</a></h3>
													<span>Massimo Artemisis</span>
													<div class="job-lctn"><i class="la la-map-marker"></i>Sacramento, California</div>
												</div>
												<div class="job-style-bx">
													<span class="job-is pt ">Part time</span>
													<span class="fav-job"><i class="la la-heart-o"></i></span>
													<i>5 months ago</i>
												</div>
											</div><!-- Job -->
											<div class="job-listing wtabs noimg">
												<div class="job-title-sec">
													<h3><a href="#" title="">Regional Sales Manager South</a></h3>
													<span>Massimo Artemisis</span>
													<div class="job-lctn"><i class="la la-map-marker"></i>Sacramento, California</div>
												</div>
												<div class="job-style-bx">
													<span class="job-is ft ">Full time</span>
													<span class="fav-job"><i class="la la-heart-o"></i></span>
													<i>5 months ago</i>
												</div>
											</div><!-- Job -->
											<div class="job-listing wtabs noimg">
												<div class="job-title-sec">
													<h3><a href="#" title="">Marketing Dairector</a></h3>
													<span>Massimo Artemisis</span>
													<div class="job-lctn"><i class="la la-map-marker"></i>Sacramento, California</div>
												</div>
												<div class="job-style-bx">
													<span class="job-is ft ">Full time</span>
													<span class="fav-job"><i class="la la-heart-o"></i></span>
													<i>5 months ago</i>
												</div>
											</div><!-- Job -->
										</div>
									 </div>
					 			</div>
							 </div>
					 	</div>
				 	</div>
				 	<div class="col-lg-4 column">
				 		<div class="job-single-head style2">
			 				<div class="job-thumb"> <img src="images\resource\TCS-logo.jpg" alt="" height="100v"> </div>
			 				<div class="job-head-info">
			 					<h4>Tata Consultancy Services Limited</h4>
			 					<span>9th Floor, Nirmal Building, Nariman Point, Mumbai  400 021, India</span>
			 					<p><i class="la la-unlink"></i> www.tcs.com</p>
			 					<p><i class="la la-phone"></i> +91-22-6778 9191 </p>
			 					<p><i class="la la-envelope-o"></i> <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="71101d185f050417101f311b1e1319041f055f121e1c">[email&#160;protected]</a></p>
			 				</div>
			 				<div class="share-bar">
				 				<a href="#" title="" class="share-google"><i class="la la-google"></i></a><a href="#" title="" class="share-fb"><i class="fa fa-facebook"></i></a><a href="#" title="" class="share-twitter"><i class="fa fa-twitter"></i></a>
				 			</div>
					 		<div class="emply-btns">
					 			<a class="seemap" href="#" title=""><i class="la la-map-marker"></i> See On Map</a>
					 			<a class="followus" href="#" title=""><i class="la la-paper-plane"></i> Follow us</a>
					 		</div>
			 			</div><!-- Job Head -->
				 	</div>
				</div>
			</div>
		</div>
	</section>

	<?php include_once('footer.php');?>

</div>

<?php include_once('login.php');?>

<?php include_once('sign_up.php');?>


<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="js\jquery.min.js" type="text/javascript"></script>
<script src="js\modernizr.js" type="text/javascript"></script>
<script src="js\script.js" type="text/javascript"></script>
<script src="js\bootstrap.min.js" type="text/javascript"></script>
<script src="js\wow.min.js" type="text/javascript"></script>
<script src="js\slick.min.js" type="text/javascript"></script>
<script src="js\parallax.js" type="text/javascript"></script>
<script src="js\select-chosen.js" type="text/javascript"></script>
<script src="js\jquery.scrollbar.min.js" type="text/javascript"></script>

</body>
</html>

